// biblis/otimizadores.h
#pragma once
#include "otimis/otimizador.h"
#include "otimis/adam.h"
#include "otimis/adamw.h"
#include "otimis/adadelta.h"
#include "otimis/sgd.h"
#include "otimis/adagrad.h"
#include "otimis/rmsprop.h"
#include "otimis/nesterov.h"